language: cpp
compiler:
  - gcc
  - clang
env:
  - QT=qt5 CONFIG=shared
  - QT=qt5 CONFIG=static
  - QT=qt5 CONFIG=coverage
  - QT=qt4 CONFIG=shared
  - QT=qt4 CONFIG=static
matrix:
  exclude:
    - compiler: clang
      env: QT=qt5 CONFIG=coverage
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev
  - if [[ "$CONFIG" == "coverage" ]]; then sudo apt-get install rubygems lcov; fi
  - if [[ "$CONFIG" == "coverage" ]]; then gem install coveralls-lcov; fi
script:
  - nproc
  - qmake -qt=${QT} -v
  - ./configure -verbose -config ${CONFIG} -qmake `qmake -qt=${QT} -query QT_INSTALL_BINS`/qmake -var "QMAKE_CXX=${CXX}" -var "QMAKE_CC=${CC}"
  - make -j$(nproc)
  - if [[ "$CONFIG" != "coverage" ]]; then make check; fi
  - if [[ "$CONFIG" != "coverage" ]]; then sudo make install; fi
  - if [[ "$CONFIG" != "coverage" ]]; then cd tests/build; fi
  - if [[ "$CONFIG" != "coverage" ]]; then qmake -qt=${QT} && make; fi
  - if [[ "$CONFIG" == "coverage" ]]; then make coverage; fi
  - if [[ "$CONFIG" == "coverage" ]]; then cat coverage/Irc*.cov > Communi.cov; fi
  - if [[ "$CONFIG" == "coverage" ]]; then coveralls-lcov Communi.cov; fi
notifications:
  email:
    recipients:
      - jpnurmi@gmail.com
    on_success: never
    on_failure: always
  irc:
    channels:
      - "irc.freenode.org#communi"
    template:
     - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} - %{build_url}"
    use_notice: true
    skip_join: true
